# Generated by Django 5.2.1 on 2025-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['-created_at'], name='main_test_created_1f3bbe_idx'),
        ),
    ]
